// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	translation "translation/internal/handler/translation"
	"translation/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/get_lang_list",
				Handler: translation.GetLangListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/translation"),
	)
}
