// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.6
// source: translation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLangListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLangListReq) Reset() {
	*x = GetLangListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLangListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLangListReq) ProtoMessage() {}

func (x *GetLangListReq) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLangListReq.ProtoReflect.Descriptor instead.
func (*GetLangListReq) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{0}
}

type LangData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lang     string `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Code     string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Original bool   `protobuf:"varint,4,opt,name=original,proto3" json:"original,omitempty"`
	Results  bool   `protobuf:"varint,5,opt,name=results,proto3" json:"results,omitempty"`
}

func (x *LangData) Reset() {
	*x = LangData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LangData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LangData) ProtoMessage() {}

func (x *LangData) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LangData.ProtoReflect.Descriptor instead.
func (*LangData) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{1}
}

func (x *LangData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LangData) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *LangData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LangData) GetOriginal() bool {
	if x != nil {
		return x.Original
	}
	return false
}

func (x *LangData) GetResults() bool {
	if x != nil {
		return x.Results
	}
	return false
}

type GetLangListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64       `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LangList []*LangData `protobuf:"bytes,2,rep,name=lang_list,json=langList,proto3" json:"lang_list,omitempty"`
}

func (x *GetLangListResp) Reset() {
	*x = GetLangListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLangListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLangListResp) ProtoMessage() {}

func (x *GetLangListResp) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLangListResp.ProtoReflect.Descriptor instead.
func (*GetLangListResp) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{2}
}

func (x *GetLangListResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetLangListResp) GetLangList() []*LangData {
	if x != nil {
		return x.LangList
	}
	return nil
}

var File_translation_proto protoreflect.FileDescriptor

var file_translation_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x22, 0x78, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61,
	0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x5e, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x09, 0x6c, 0x61, 0x6e, 0x67,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x57, 0x0a, 0x0b,
	0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x67,
	0x65, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x67,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_translation_proto_rawDescOnce sync.Once
	file_translation_proto_rawDescData = file_translation_proto_rawDesc
)

func file_translation_proto_rawDescGZIP() []byte {
	file_translation_proto_rawDescOnce.Do(func() {
		file_translation_proto_rawDescData = protoimpl.X.CompressGZIP(file_translation_proto_rawDescData)
	})
	return file_translation_proto_rawDescData
}

var file_translation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_translation_proto_goTypes = []interface{}{
	(*GetLangListReq)(nil),  // 0: translation.GetLangListReq
	(*LangData)(nil),        // 1: translation.LangData
	(*GetLangListResp)(nil), // 2: translation.GetLangListResp
}
var file_translation_proto_depIdxs = []int32{
	1, // 0: translation.GetLangListResp.lang_list:type_name -> translation.LangData
	0, // 1: translation.userService.getLangList:input_type -> translation.GetLangListReq
	2, // 2: translation.userService.getLangList:output_type -> translation.GetLangListResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_translation_proto_init() }
func file_translation_proto_init() {
	if File_translation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_translation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLangListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_translation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LangData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_translation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLangListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_translation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translation_proto_goTypes,
		DependencyIndexes: file_translation_proto_depIdxs,
		MessageInfos:      file_translation_proto_msgTypes,
	}.Build()
	File_translation_proto = out.File
	file_translation_proto_rawDesc = nil
	file_translation_proto_goTypes = nil
	file_translation_proto_depIdxs = nil
}
