// Code generated by goctl. DO NOT EDIT.
package types

type GetLangListReq struct {
}

type LangData struct {
	Lang string `json:"lang"`
	Code string `json:"code"`
}

type GetLangListResp struct {
	LangList []LangData `json:"lang_list"`
}
