// Code generated by goctl. DO NOT EDIT.
package types

type GetLangListReq struct {
	Platform string `form:"platform"`
}

type LangData struct {
	Lang     string `json:"lang"`
	Code     string `json:"code"`
	Original bool   `json:"original"`
	Results  bool   `json:"results"`
}

type GetLangListResp struct {
	LangList []LangData `json:"lang_list"`
}

type PlatformData struct {
	Name    string `json:"name"`
	Code    string `json:"code"`
	Default bool   `json:"default"`
}

type GetPlatformListResp struct {
	Platformist []PlatformData `json:"platform_list"`
}

type TranslationJsonReq struct {
	IsKeyAsTr bool   `json:"isKeyAsTr"`
	Original  string `json:"original"`
	Results   string `json:"results"`
	Json      string `json:"json"`
}

type TranslationJsonResp struct {
	Json string `json:"json"`
}
