// Code generated by goctl. DO NOT EDIT.
// Source: translation.proto

package userservice

import (
	"context"

	"translation/rpc/translation/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetLangListReq  = pb.GetLangListReq
	GetLangListResp = pb.GetLangListResp
	LangData        = pb.LangData

	UserService interface {
		GetLangList(ctx context.Context, in *GetLangListReq, opts ...grpc.CallOption) (*GetLangListResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) GetLangList(ctx context.Context, in *GetLangListReq, opts ...grpc.CallOption) (*GetLangListResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetLangList(ctx, in, opts...)
}
