// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginReq struct {
	Email   string `json:"email"`
	Passwod string `json:"password"`
}

type UserLoinResp struct {
	Token string `json:"token"`
}

type UserRegisterReq struct {
	Email         string `json:"email"`
	Password      string `json:"password"`
	PasswordCheck string `json:"password_check"`
}

type UserRegisterResp struct {
	Token string `josn:"tokne"`
}
