// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginReq struct {
	Email    string `json:"email" validate:"email"`
	Password string `json:"password" validate:"min=6"`
}

type UserLoginResp struct {
	Id    int64  `json:"id"`
	Email string `json:"email"`
	Token string `json:"token"`
}

type UserRegisterReq struct {
	Email         string `json:"email" validate:"email"`
	Password      string `json:"password" validate:"min=6"`
	PasswordCheck string `json:"password_check" validate:"min=6"`
}

type UserRegisterResp struct {
	Id    int64  `json:"id"`
	Email string `josn:"email"`
	Token string `josn:"tokne"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	Email string `json:"email"`
}
