// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginReq struct {
	Email   string `json:"email" validate:"email"`
	Passwod string `json:"password" validate:"min=6"`
}

type UserLoinResp struct {
	Token string `json:"token"`
}

type UserRegisterReq struct {
	Email         string `json:"email" validate:"email"`
	Password      string `json:"password" validate:"min=6"`
	PasswordCheck string `json:"password_check" validate:"min=6"`
}

type UserRegisterResp struct {
	Token string `josn:"tokne"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	Email string `json:"email"`
}
