// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	userslogin "translation/api/internal/handler/users/login"
	"translation/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: userslogin.UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: userslogin.UserRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/users"),
	)
}
