// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	translationlang "translation/api/internal/handler/translation/lang"
	userinfo "translation/api/internal/handler/user/info"
	userlogin "translation/api/internal/handler/user/login"
	"translation/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: userlogin.UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: userlogin.UserRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/get_user_info",
				Handler: userinfo.UserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/get_lang_list",
				Handler: translationlang.GetLangListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/translation"),
	)
}
